# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxTableViewWithSection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxTableViewWithSection
  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa', '~> 3.0'
  pod 'RxDataSources'

  target 'RxTableViewWithSectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxTableViewWithSectionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
