# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxNumbers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxNumbers
  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa', '~> 3.0'

  target 'RxNumbersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxNumbersUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
