# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxHelloMVVM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxHelloMVVM
  pod 'RxSwift', '~> 3.0'
  pod 'RxCocoa', '~> 3.0'

  target 'RxHelloMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxHelloMVVMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
